### ISSUE TITLE
Interchange Responsive Content

### ISSUE THREAD

**Issue by williamjwood76** [agencyrevolution/foundation-dnn#8]
Not so much a issue, rather a question. Will you be open sourcing Interchange Responsive Content for DNN?

**Comment by stephenway** [comment]
It's already open source, if you find a a good use for it in this project send us a PR.

**Comment by williamjwood76** [comment]
I was actually referring to this http://foundation.agencyrevolution.com/docs/interchange-responsive-content

**Comment by stephenway** [comment]
Oh yea, eventually we will open source that set of components, but it won't be an easy out of the box solution if that's what your looking for right now.
